seed_everything: null
trainer:
  logger:
      - class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
            project: aspect_detection
            name: combined_muril_bias_adj
  devices: [1]
  max_epochs: 60
  accelerator: "gpu"
  strategy: null
model:
  model_name_or_path: google/muril-base-cased
  learning_rate: 5.0e-05
  warmup_ratio: 0.1
  weight_decay: 0.01
  lambda_weight: 2.0
  word_dropout_rate: 0.1
  sent_dropout_rate: 0.2
  calc_word_bias: true
  calc_sent_bias: true
data:
  dataset_path: sharmila_df
  data_dir: datasets/
  model_name_or_path: google/muril-base-cased
  val_ratio: 0.2
  batch_size: 50
ckpt_path: null
