# pytorch_lightning==1.8.6
seed_everything: 4242
trainer:
  logger: False
  devices: [1]
  max_epochs: 60
  accelerator: gpu
  # strategy: ddp_find_unused_parameters_false
  log_every_n_steps: 33
  fast_dev_run: True
ckpt_path: null
model:
  class_path: models.sent_model.SentModel
  init_args:
    model_name_or_path: ${data.init_args.model_name_or_path}
    dropout_rate: 0.3
    learning_rate: 5.0e-05
    weight_decay: 0.01
    sexual_weight: 0.1
    calc_bias: True
    plateu_factor: 0.1
    plateu_patience: 2
    monitor: val_loss
data:
  class_path: datamodules.sent_datamodule.SentDataModule
  init_args:
    dataset_path: datasets/sentence
    val_ratio: 0.1
    current_fold: 5
    model_name_or_path: google/muril-base-cased
    batch_size: 64
    max_workers: 4
    pin_memory: False