# pytorch_lightning==1.7.4
seed_everything: 42
trainer:
  logger: False
  devices: [0]
  max_epochs: 60
  accelerator: gpu
  log_every_n_steps: 33
  fast_dev_run: True
ckpt_path: null
model:
  class_path: models.word_model.WordModel
  init_args:
    model_name_or_path: ${data.init_args.model_name_or_path}
    dropout_rate: 0.2
    learning_rate: 5.0e-05
    weight_decay: 0.01
    plateu_factor: 0.1
    plateu_patience: 2
    monitor: val_loss
    calc_bias: true
data:
  class_path: datamodules.word_datamodule.WordDataModule
  init_args:
    dataset_path: datasets/word
    val_ratio: 0.1
    model_name_or_path: google/muril-base-cased
    batch_size: 32
    max_workers: 4
    pin_memory: false
