# pytorch_lightning==1.7.2
seed_everything: 42
trainer:
  logger:
      - class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
            project: aspect_detection
            name: sent_muril
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: val_loss
        mode: min
        dirpath: checkpoints/sent_muril
        save_weights_only: True
        filename: "{epoch:02d}-{val_loss:.3f}"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
        verbose: True
  devices: auto
  max_epochs: 60
  accelerator: "gpu"
  strategy: ddp_find_unused_parameters_false
  fast_dev_run: True
ckpt_path: null
model:
  class_path: models.sent_model.SentModel
  init_args:
    model_name_or_path: $data.init_args.model_name_or_path
    dropout_rate: 0.4
    learning_rate: 5.0e-05
    warmup_ratio: 0.1
    weight_decay: 0.01
data:
  class_path: data.sent_datamodule.SentDataModule
  init_args:
    data_dir: datasets/
    val_ratio: 0.1
    model_name_or_path: google/muril-base-cased
    batch_size: 64
    max_workers: 4
    pin_memory: True
